@ganache_rpc = http://127.0.0.1:8545
@host = http://localhost:3000

### Get ganache chain id
POST {{ganache_rpc}}
Content-Type: application/json

{
    "jsonrpc":"2.0",
    "method":"eth_chainId",
    "params":[],
    "id":1
}

### create new market
POST  {{host}}/prediction-market/
Content-Type: application/json

{
    "question": "My first approved question?",
    "initialLiquidity": 1,
    "outcomes": [
        "Yes", "No"
    ],
    "resolveAt": "2024-12-26T20:30:00.000Z"
}

### Get markets:
GET  {{host}}/prediction-market/