@host = http://localhost:3000

### create new market
POST  {{host}}/binary-prediction/
Content-Type: application/json

{
    "question": "My first approved question",
    "initialLiquidity": 1,
    "outcomes": [
        "Yes", "No"
    ]
}