@ganache_rpc = http://127.0.0.1:8545
@host = http://localhost:3000

### Get ganache chain id
POST {{ganache_rpc}}
Content-Type: application/json

{
    "jsonrpc":"2.0",
    "method":"eth_chainId",
    "params":[],
    "id":1
}

### create new market
POST  {{host}}/prediction-market/
Content-Type: application/json

{
    "question": "Question 3?",
    "initialLiquidity": 1,
    "outcomes": [
        "Yes", "No"
    ],
    "resolveAt": "2024-12-26T20:30:00.000Z"
}

### Get markets:
GET  {{host}}/prediction-market/

### Sell tokens
POST  {{host}}/prediction-market/ctf/sell
Content-Type: application/json

{
    "marketId": 1,
    "outcomeIndex": 0,
    "amount": 0.1
}

### Buy tokens
POST  {{host}}/prediction-market/ctf/buy
Content-Type: application/json

{
    "marketId": 2,
    "outcomeIndex": 1,
    "amount": 1.1
}

### Get balance of a conditional token
GET {{host}}/prediction-market/ctf/balance?market=2&indexset=1