@host = http://localhost:3000

### Create/Register user:
POST {{host}}/user/register
Content-Type: application/json

{
    "email": "test@gmail.com",
    "username": "me",
    "password": "iamhereX_1",
    "walletAddress": "0x22d491Bde2303f2f43325b2108D26f1eAbA1e32b"
}

### Get a specific user by id
GET {{host}}/user/2

### Login user:
GET {{host}}/user/login?username=me&&password=iamhereX_1


### Tell me who am i?
GET {{host}}/user/whoami

### Log out
POST {{host}}/user/logout

### lLogin By Post
POST {{host}}/user/login
Content-Type: application/json

{
    "email": "test@gmail.com",
    "password": "iamhereX_1"
}

### Get users with specific username
GET {{host}}/user?username=what

### Get users with specific email
GET {{host}}/user?email=whatever@gmail.com


### Update a user
PATCH {{host}}/user/2
Content-Type: application/json

{
    "password": "This_x_WHatevr3"
}

### Update a user, multiple changes:
PATCH {{host}}/user/1
Content-Type: application/json

{
    "email": "another@gmail.com",
    "username": "whatever"
}

### Delete a user
DELETE {{host}}/user/2


### Add usere badge
POST {{host}}/user/badge
Content-Type: application/json

{
    "name": "test badge for forth user"
}

### Get all badges
GET {{host}}/user/badge


### Delete Account
DELETE {{host}}/user/3/delete-account
Content-Type: application/json

{
    "password": "iamhereX_1"
}